apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-agent-role
rules:
# ImageStream operations
- apiGroups: ["image.openshift.io"]
  resources: ["imagestreams", "imagestreamimages", "imagestreamtags"]
  verbs: ["get", "list", "create", "update", "patch", "push"]
# Deployment operations
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/rollback"]
  verbs: ["get", "list", "watch", "patch", "update"]
# BuildConfig operations
- apiGroups: ["build.openshift.io"]
  resources: ["buildconfigs", "buildconfigs/instantiate", "builds"]
  verbs: ["get", "list", "create", "update", "patch"]
# Pod operations
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["get", "list", "watch"]
# Service operations
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-agent-role
subjects:
- kind: ServiceAccount
  name: jenkins-agent
  namespace: default
