openapi: 3.0.3
info:
  title: PartyAPI
  description: API for managing parties 
  version: 1.0.0

servers:
  - url: https://dev6056135.a-fra-c1.int.ipaas.automation.ibm.com
    description: Development server

security:
  - oauth2: []

paths:

  /parties:
    post:
      summary: Create a new party
      description: Create a new party 
      tags:
        - Parties
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartyInput'
            example:
              name: Bob
              type: individual
              status: active
      responses:
        '201':
          description: Party created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Party'
              example:
                id: f71d5173-e0ef-411d-894b-f0c6cc636da8
                name: Bob
                type: individual
                status: active
                creationDateTime: 2025-11-11 07:43:50
                updateDateTime: 2025-11-11 07:43:50
        '400':
          description: Bad request - Invalid input
        '401':
          description: Unauthorized - Missing or invalid token
        '403':
          description: Forbidden - Invalid webhook key

components:
  securitySchemes:
    oauth2:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OAuth 2.0 Bearer token

  schemas:
    PartyInput:
      type: object
      required:
        - name
        - type
        - status
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
          example: Bob
          description: Name of the party
        type:
          type: string
          enum: [individual, public, private]
          example: individual
          description: Type of party
        status:
          type: string
          enum: [active, inactive]
          example: active
          description: Status of the party

    Party:
      allOf:
        - $ref: '#/components/schemas/PartyInput'
        - type: object
          required:
            - id
            - name
            - type
            - status
            - creationDateTime
          properties:
            id:
              type: string
              format: uuid
              example: f71d5173-e0ef-411d-894b-f0c6cc636da8
              description: Unique identifier (UUID v4)
            creationDateTime:
              type: string
              example: 2025-11-11 07:43:50
              description: Timestamp when the party was created
            updateDateTime:
              type: string
              example: 2025-11-11 07:43:50
              description: Timestamp when the party was last updated